# Generated by Django 4.1 on 2023-12-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_score_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="docId",
        ),
        migrations.AddField(
            model_name="score",
            name="title",
            field=models.CharField(default="Default", max_length=255),
            preserve_default=False,
        ),
    ]
